DROP DATABASE ToDoDB;
CREATE DATABASE ToDoDB;
USE ToDoDB;

SET NAMES 'utf8';

CREATE TABLE Users(
    id INT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role VARCHAR(5) NOT NULL DEFAULT "USER",
    PRIMARY KEY(id)
) DEFAULT CHARSET=utf8;

CREATE TABLE Doings(
    id INT NOT NULL UNIQUE AUTO_INCREMENT,
    doingText VARCHAR(1000) NOT NULL,
    doingDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    isCompleted BOOLEAN DEFAULT false,
    userId INT,
    PRIMARY KEY (id),
    FOREIGN KEY(userId) REFERENCES Users(id)
) DEFAULT CHARSET=utf8;